const SUPABASE_URL = "https://wukndecvayhuygpxtzcn.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_CmFZBp44Ql4THLVIAkYkUg_pP4R_Wws";
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const branches=[{id:1,name:'لقی ١'},{id:2,name:'لقی ٢'}];
const users=[{name:'Admin',pin:'1234',role:'admin',branchId:'all'},{name:'Cashier Branch 1',pin:'1111',role:'cashier',branchId:1},{name:'Cashier Branch 2',pin:'2222',role:'cashier',branchId:2}];
let data={products:[],sales:[],customers:[],expenses:[]}, session=null, activeBranch=1, tab='dashboard', cart=[];
const $=id=>document.getElementById(id); const money=n=>'$'+Number(n||0).toFixed(2); const branchName=id=>id==='all'?'هەموو لقەکان':(branches.find(b=>b.id==id)?.name||id);
function scoped(arr){return session?.role==='admin'&&activeBranch==='all'?arr:arr.filter(x=>Number(x.branch_id)===Number(activeBranch))}
function el(h){$('app').innerHTML=h}
async function initBranches(){for(const b of branches){await db.from('branches').upsert({id:b.id,name:b.name},{onConflict:'id'})}}
async function loadData(){await initBranches(); let [p,s,c,e]=await Promise.all([db.from('products').select('*').order('id',{ascending:false}),db.from('sales').select('*').order('id',{ascending:false}),db.from('customers').select('*').order('id',{ascending:false}),db.from('expenses').select('*').order('id',{ascending:false})]); if(p.error||s.error||c.error||e.error){alert('کێشەی پەیوەندی بە Supabase. دڵنیابە RLS policies ـەکانت run کردووە.'); console.log(p.error,s.error,c.error,e.error)} data.products=p.data||[];data.sales=s.data||[];data.customers=c.data||[];data.expenses=e.data||[]}
async function login(){const name=$('loginName').value.trim(),pin=$('pin').value.trim();const u=users.find(x=>x.name.toLowerCase()===name.toLowerCase()&&x.pin===pin); if(!u)return alert('ناو یان PIN هەڵەیە'); session=u;activeBranch=u.role==='admin'?1:u.branchId; await loadData(); render()}
function logout(){session=null;cart=[];renderLogin()}
function renderLogin(){el(`<div class="login"><h1>سیستەمی POS نێرگەلە</h1><p class="muted">Supabase Online Version</p><input id="loginName" value="Admin" placeholder="ناوی بەکارهێنەر"><input id="pin" value="1234" placeholder="PIN" type="password"><button onclick="login()">چوونەژوورەوە</button><p class="muted ltr">Admin / 1234<br>Cashier Branch 1 / 1111<br>Cashier Branch 2 / 2222</p></div>`)}
function render(){if(!session)return renderLogin();const tabs=['dashboard:داشبۆرد','pos:فرۆشتن','products:کاڵاکان','inventory:کۆگا','customers:کڕیار/قەرز','expenses:خەرجی','reports:ڕاپۆرت'];el(`<div class="app"><div class="topbar"><div><b>POS نێرگەلە</b><div class="muted">${session.name} - ${session.role} - ${branchName(activeBranch)}</div></div><div>${session.role==='admin'?`<select onchange="activeBranch=this.value==='all'?'all':Number(this.value);cart=[];render()"><option value="1" ${activeBranch===1?'selected':''}>لقی ١</option><option value="2" ${activeBranch===2?'selected':''}>لقی ٢</option><option value="all" ${activeBranch==='all'?'selected':''}>هەموو لقەکان</option></select>`:''}</div><button class="danger" onclick="logout()">دەرچوون</button></div><div class="tabs">${tabs.map(t=>{let[a,b]=t.split(':');return`<button class="${tab===a?'active':''}" onclick="tab='${a}';render()">${b}</button>`}).join('')}</div><br><div id="view">${view()}</div></div>`)}
function view(){return ({dashboard:dashboard(),pos:pos(),products:products(),inventory:inventory(),customers:customers(),expenses:expenses(),reports:reports()})[tab]}
function stats(){let s=scoped(data.sales),e=scoped(data.expenses);let sales=s.reduce((a,x)=>a+Number(x.total||0),0), exp=e.reduce((a,x)=>a+Number(x.amount||0),0);return{sales,profit:sales-exp,orders:s.length,exp}}
function dashboard(){let st=stats(),low=scoped(data.products).filter(p=>Number(p.stock)<=10);return `<div class="grid four"><div class="card stat"><span class="muted">فرۆشتن</span><h2>${money(st.sales)}</h2></div><div class="card stat"><span class="muted">قازانج</span><h2>${money(st.profit)}</h2></div><div class="card stat"><span class="muted">وەسڵ</span><h2>${st.orders}</h2></div><div class="card stat"><span class="muted">خەرجی</span><h2>${money(st.exp)}</h2></div></div><br><div class="card"><h3>ئاگاداری کۆگای کەم</h3>${low.length?low.map(p=>`<p class="low">${p.name} - ماوە: ${p.stock} ${p.unit_type}</p>`).join(''):'<p class="ok">هیچ کاڵایەک کەم نییە</p>'}</div>`}
function pos(){let ps=scoped(data.products).filter(p=>activeBranch!=='all');let total=cart.reduce((a,i)=>a+i.qty*i.sale_price,0);return activeBranch==='all'?'<div class="card">تکایە لقێک هەڵبژێرە بۆ فرۆشتن.</div>':`<div class="pos"><div class="card"><h3>کاڵاکان</h3><input oninput="renderProductsList(this.value)" placeholder="گەڕان"><div id="plist" class="products">${productCards(ps)}</div></div><div class="card"><h3>سەبەتە</h3>${cart.map(i=>`<div class="cart-item"><b>${i.name}</b><span class="qty"><button class="btn2" onclick="changeQty(${i.id},-1)">-</button>${i.qty}<button class="btn2" onclick="changeQty(${i.id},1)">+</button></span><span>${money(i.qty*i.sale_price)}</span></div>`).join('')||'<p class="muted">هیچ کاڵایەک نییە</p>'}<hr><h2>${money(total)}</h2><input id="cust" placeholder="ناوی کڕیار / قەرز"><select id="pay"><option value="cash">cash</option><option value="card">card</option><option value="debt">debt</option></select><button onclick="checkout()">تەواوکردنی فرۆشتن</button><button class="btn2" onclick="cart=[];render()">پاککردنەوە</button></div></div>`}
function productCards(ps){return ps.map(p=>`<div class="product" onclick="addCart(${p.id})"><b>${p.name}</b><span class="pill">${money(p.sale_price)} / ${p.unit_type}</span><p class="muted">کۆگا: ${p.stock}</p></div>`).join('')}
function renderProductsList(q){$('plist').innerHTML=productCards(scoped(data.products).filter(p=>activeBranch!=='all'&&p.name.includes(q)))}
function addCart(id){let p=data.products.find(x=>x.id==id);let qty=p.unit_type==='gram'?50:1;let ex=cart.find(x=>x.id==id);ex?ex.qty+=qty:cart.push({...p,qty});render()}
function changeQty(id,n){let i=cart.find(x=>x.id==id);if(!i)return;i.qty+=n*(i.unit_type==='gram'?50:1);if(i.qty<=0)cart=cart.filter(x=>x.id!=id);render()}
async function checkout(){let total=cart.reduce((a,i)=>a+i.qty*i.sale_price,0); if(!cart.length)return alert('سەبەتە بەتاڵە'); for(const i of cart){if(Number(i.stock)<i.qty)return alert('کۆگا بەس نییە: '+i.name)} for(const i of cart){let newStock=Number(i.stock)-i.qty; await db.from('products').update({stock:newStock}).eq('id',i.id)} let pay=$('pay').value,cust=$('cust').value.trim(); let customerId=null; if(pay==='debt'&&cust){let c=data.customers.find(x=>x.name===cust&&Number(x.branch_id)===Number(activeBranch)); if(!c){let r=await db.from('customers').insert({branch_id:activeBranch,name:cust,phone:'',debt:0}).select().single(); c=r.data} customerId=c.id; await db.from('customers').update({debt:Number(c.debt||0)+total}).eq('id',c.id)} await db.from('sales').insert({branch_id:activeBranch,customer_id:customerId,total,payment_method:pay}); cart=[]; await loadData(); alert('فرۆشتن تەواو بوو و لە Supabase هەڵگیرا'); render()}
function products(){return `<div class="card"><h3>زیادکردنی کاڵا</h3>${activeBranch==='all'?'<p>لقێک هەڵبژێرە</p>':`<div class="grid three"><input id="pn" placeholder="ناوی کاڵا"><input id="pc" placeholder="جۆر"><select id="pu"><option value="piece">دانە</option><option value="gram">گرام</option><option value="kg">کیلۆ</option></select><input id="ps" type="number" placeholder="کۆگا"><input id="pcost" type="number" placeholder="نرخی کڕین"><input id="pprice" type="number" placeholder="نرخی فرۆشتن"></div><button onclick="addProduct()">زیادکردن</button>`}</div><br>${tableProducts()}`}
async function addProduct(){await db.from('products').insert({branch_id:activeBranch,name:$('pn').value,category:$('pc').value,unit_type:$('pu').value,stock:+$('ps').value,cost_price:+$('pcost').value,sale_price:+$('pprice').value}); await loadData(); render()}
function tableProducts(){return `<div class="card"><table class="table"><tr><th>ناو</th><th>لق</th><th>یەکە</th><th>کۆگا</th><th>نرخ</th><th></th></tr>${scoped(data.products).map(p=>`<tr><td>${p.name}</td><td>${branchName(Number(p.branch_id))}</td><td>${p.unit_type}</td><td>${p.stock}</td><td>${money(p.sale_price)}</td><td><button class="danger" onclick="delProduct(${p.id})">سڕینەوە</button></td></tr>`).join('')}</table></div>`}
async function delProduct(id){await db.from('products').delete().eq('id',id); await loadData(); render()}
function inventory(){return `<div class="card"><h3>کۆگا</h3><table class="table"><tr><th>کاڵا</th><th>لق</th><th>ماوە</th><th>زیادکردنی کۆگا</th></tr>${scoped(data.products).map(p=>`<tr><td>${p.name}</td><td>${branchName(Number(p.branch_id))}</td><td>${p.stock} ${p.unit_type}</td><td><input id="st${p.id}" type="number" placeholder="بڕ"><button onclick="addStock(${p.id})">زیاد</button></td></tr>`).join('')}</table></div>`}
async function addStock(id){let p=data.products.find(x=>x.id==id),v=+$('st'+id).value; await db.from('products').update({stock:Number(p.stock)+v}).eq('id',id); await loadData(); render()}
function customers(){return `<div class="card"><h3>کڕیار و قەرز</h3><table class="table"><tr><th>ناو</th><th>لق</th><th>قەرز</th><th>پارەدان</th></tr>${scoped(data.customers).map(c=>`<tr><td>${c.name}</td><td>${branchName(Number(c.branch_id))}</td><td>${money(c.debt)}</td><td><input id="pay${c.id}" type="number"><button onclick="payDebt(${c.id})">پارەدان</button></td></tr>`).join('')}</table></div>`}
async function payDebt(id){let c=data.customers.find(x=>x.id==id),v=+$('pay'+id).value; await db.from('customers').update({debt:Math.max(0,Number(c.debt)-v)}).eq('id',id); await loadData(); render()}
function expenses(){return `<div class="card"><h3>خەرجی</h3>${activeBranch==='all'?'لقێک هەڵبژێرە':`<input id="exn" placeholder="ناوی خەرجی"><input id="exa" type="number" placeholder="بڕ"><button onclick="addExpense()">زیادکردن</button>`}<table class="table"><tr><th>ناو</th><th>بڕ</th><th>لق</th><th>بەروار</th></tr>${scoped(data.expenses).map(e=>`<tr><td>${e.title}</td><td>${money(e.amount)}</td><td>${branchName(Number(e.branch_id))}</td><td>${new Date(e.created_at).toLocaleString()}</td></tr>`).join('')}</table></div>`}
async function addExpense(){await db.from('expenses').insert({branch_id:activeBranch,title:$('exn').value,amount:+$('exa').value}); await loadData(); render()}
function reports(){let st=stats();return `<div class="grid three"><div class="card"><h3>فرۆشتن</h3><h2>${money(st.sales)}</h2></div><div class="card"><h3>قازانج</h3><h2>${money(st.profit)}</h2></div><div class="card"><h3>قەرز</h3><h2>${money(scoped(data.customers).reduce((a,c)=>a+Number(c.debt||0),0))}</h2></div></div>`}
renderLogin();
